playbook:
  created_date: "20240320"
  description: |
    This playbook will deploy kserve rawDeployment mode with ODH.

    tested operator version:
    - OHD 2.9.0
  steps:
    - unit:
       name: install-odh-stable-operator-without-dsci
       description: Install ODH operator fast version
       input_env:
            CHANNEL: "fast"
    - role:
        name: opendatahub-create-dsci 
        description: Create a DSCI set servicemesh to "Removed"
        input_env:
            ENABLE_SERVICEMESH: Removed                  
            OPENDATAHUB_TYPE: "opendatahub"
    - role:
        name: opendatahub-create-dsc
        description: Create a DSC setting knative to "Removed" and defaultDeploymentMode to "RawDeployment"
        input_env:
            ENABLE_KSERVE: Managed
            ENABLE_KSERVE_KNATIVE: Removed         
            DEFAULT_DEPLOYMENTMODE: RawDeployment
            OPENDATAHUB_TYPE: "opendatahub"
  
